package com.salaboy.process;

import com.salaboy.model.*;
import org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl;

rule "Calculate Todays Score - Based on Plan"
    no-loop
    when
        $pi: WorkflowProcessInstanceImpl($person: variables['person'])
        $t: RatesToday($a: rateA, $b: rateB)
        $p: Person(name == ((Person)$person).getName(), $age: age, plan != null, score == 0)
    then
        $p.setScore($a * $age);
        $pi.setVariable("person", $p);
        update($p);
end