/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.salaboy.jbpm5.dev.guide;

import com.salaboy.jbpm5.dev.guide.tablemodel.SimpleTaskSummariesModel;
import com.salaboy.jbpm5.dev.guide.tablemodel.TaskSummariesModel;
import com.salaboy.jbpm5.dev.guide.tablemodel.DetailedTaskSummariesModel;
import com.salaboy.jbpm5.dev.guide.tablemodel.FormRegistryTableModel;
import com.salaboy.jbpm5.dev.guide.tablemodel.TaskParametersTableModel;
import com.salaboy.jbpm5.dev.guide.taskform.DynamicTaskForm;
import com.salaboy.jbpm5.dev.guide.taskform.MySimpleTaskFormJPanel;
import com.salaboy.jbpm5.dev.guide.taskform.OtherTaskForm;
import java.awt.Component;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.drools.SystemEventListenerFactory;
import org.jbpm.task.*;
import org.jbpm.task.event.DefaultTaskEventListener;
import org.jbpm.task.event.entity.TaskUserEvent;
import org.jbpm.task.query.TaskSummary;
import org.jbpm.task.service.ContentData;
import org.jbpm.task.service.TaskService;
import org.jbpm.task.service.TaskServiceSession;
import org.jbpm.task.service.local.LocalTaskService;
import org.jbpm.task.utils.ContentMarshallerHelper;

/**
 *
 * @author salaboy
 */
public class TasksListUI extends javax.swing.JFrame {

    /**
     * Custom task event listener to react upon events generated by 
     * the Task Service.
     */
    private class UITaskEventListener extends DefaultTaskEventListener{

        @Override
        public void taskCompleted(TaskUserEvent event) {
            //when a task is completed we want to close the opened form
            Component taskForm = openedTaskForms.remove(event.getTaskId());
            tasklistsjTabbedPane.remove(taskForm);
            
            //go back to task list
            tasklistsjTabbedPane.setSelectedIndex(0);
            
            //display a message
            JOptionPane.showMessageDialog(TasksListUI.this, "Task "+event.getTaskId()+" was Completed","Task Completed",JOptionPane.INFORMATION_MESSAGE);
        }

        @Override
        public void taskFailed(TaskUserEvent event) {
            //display a message
            JOptionPane.showMessageDialog(TasksListUI.this, "Task "+event.getTaskId()+" Failed!","Task Failed",JOptionPane.WARNING_MESSAGE);
        }
        
        
    }
    
    private EntityManagerFactory emf;
    private TaskService taskService;
    private TaskServiceSession taskSession;
    private Map<String, User> users = new LinkedHashMap<String, User>();
    private Map<String, Group> groups = new LinkedHashMap<String, Group>();

    private TaskParametersTableModel taskParametersTableModel;
    
    private LocalTaskService localTaskService;
    private Map<String, Class> taskForms = new LinkedHashMap<String, Class>();
    
    private FormRegistryTableModel formRegistryTableModel;
    
    private DefaultComboBoxModel userComboBoxModel = new DefaultComboBoxModel();
    
    private Map<Long, Component> openedTaskForms = new HashMap<Long, Component>();

    private UITaskEventListener taskEventListener = new UITaskEventListener();
    
    /**
     * Creates new form TasksListUI
     */
    public TasksListUI() {
        initComponents();
        initTaskComponents();
        initTaskFormMappings();
        refreshTaskList();
        
        //Refresh the task list every time tab1 is selected
        this.tasklistsjTabbedPane.addChangeListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                if (tasklistsjTabbedPane.getSelectedComponent() == jPanel1){
                    refreshTaskList();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tasklistsjTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        refreshjButton = new javax.swing.JButton();
        selectedUserjComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taskSummariesjTable = new javax.swing.JTable();
        perspectivejComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        userjTextField = new javax.swing.JTextField();
        addUserjButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        groupjTextField = new javax.swing.JTextField();
        addGroupjButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFormsRegistry = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTaskName = new javax.swing.JTextField();
        cboAssignTo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblParameters = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnAddParamter = new javax.swing.JButton();
        btnDeleteParameter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tasks Console");

        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        selectedUserjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "salaboy", "watman" }));
        selectedUserjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedUserjComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("User:");

        taskSummariesjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        taskSummariesjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TasksListUI.this.mouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(taskSummariesjTable);

        perspectivejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple", "Detailed" }));

        jLabel3.setText("Perspective: ");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(perspectivejComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(47, 47, 47)
                        .add(refreshjButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 226, Short.MAX_VALUE)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(selectedUserjComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(selectedUserjComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(perspectivejComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(refreshjButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );

        tasklistsjTabbedPane.addTab("Tasks List", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Admin Parameters"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Users and Groups"));

        jLabel4.setText("User: ");

        addUserjButton.setText("Add User");
        addUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserjButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Group: ");

        addGroupjButton.setText("Add Group");
        addGroupjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroupjButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(userjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(addUserjButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(groupjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(addGroupjButton)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(userjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(addUserjButton)
                    .add(jLabel5)
                    .add(groupjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(addGroupjButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Task Forms Registry"));

        tblFormsRegistry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblFormsRegistry);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Create New Task"));

        jButton1.setText("Add Task");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Task Name:");

        jLabel6.setText("Assign To:");

        cboAssignTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblParameters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblParameters);

        jLabel7.setText("Task Parameters:");

        btnAddParamter.setText("+");
        btnAddParamter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddParamterActionPerformed(evt);
            }
        });

        btnDeleteParameter.setText("-");
        btnDeleteParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteParameterActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtTaskName))
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel7)
                                    .add(jPanel5Layout.createSequentialGroup()
                                        .add(jLabel6)
                                        .add(23, 23, 23)
                                        .add(cboAssignTo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jButton1))
                                .add(0, 0, Short.MAX_VALUE)))
                        .add(76, 76, 76)
                        .add(btnAddParamter)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnDeleteParameter))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txtTaskName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(cboAssignTo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnAddParamter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(btnDeleteParameter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(jButton1)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tasklistsjTabbedPane.addTab("Admin", jPanel2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tasklistsjTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tasklistsjTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
        refreshTaskList();
    }//GEN-LAST:event_refreshjButtonActionPerformed

    private void selectTaskForm(JTable target, int row) {
        
        long taskId = ((TaskSummariesModel)target.getModel()).getTaskId(row);
        String taskName = ((TaskSummariesModel)target.getModel()).getTaskName(row);
        String selectedUser = (String) selectedUserjComboBox.getItemAt(selectedUserjComboBox.getSelectedIndex());
        System.out.println("Selected User: " + selectedUser);
        Class clazz = taskForms.get(taskName);
        
        if (clazz == null){
            //no custom form for this task. Let's see if there is a default
            //form defined.
            clazz = taskForms.get("*");
            if (clazz == null){
                JOptionPane.showMessageDialog(this, "No form defined for '"+taskName+" and not default (*) form is configured.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        Constructor constructor = null;
        try {
            constructor = clazz.getConstructor(LocalTaskService.class, long.class, String.class);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(TasksListUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(TasksListUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        JPanel taskForm = null;
        try {
            taskForm = (JPanel) constructor.newInstance(localTaskService,taskId, selectedUser);
        } catch (InstantiationException ex) {
            Logger.getLogger(TasksListUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(TasksListUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(TasksListUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(TasksListUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //new MyTaskFormJPanel(localTaskService, taskId, selectedUser);
        tasklistsjTabbedPane.add(taskForm);
        tasklistsjTabbedPane.setSelectedComponent(taskForm);
        
        openedTaskForms.put(taskId, taskForm);
    }

    private void selectedUserjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedUserjComboBoxActionPerformed
        this.refreshTaskList();
    }//GEN-LAST:event_selectedUserjComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Create a new Task
        Task task = new Task();
        task.setPriority(1);
        List<I18NText> names = new ArrayList<I18NText>();
        names.add(new I18NText("en-UK", this.txtTaskName.getText()));
        task.setNames(names);
        task.setDescriptions(names);
        task.setSubjects(names);
        
        //Create people assignments
        PeopleAssignments peopleAssignments = new PeopleAssignments();
        List<OrganizationalEntity> usersEntities = new ArrayList<OrganizationalEntity>();
        usersEntities.add(users.get((String)cboAssignTo.getSelectedItem()));
        peopleAssignments.setPotentialOwners(usersEntities);
        
        //Admin entity
        List<OrganizationalEntity> adminsEntities = new ArrayList<OrganizationalEntity>();
        adminsEntities.add(users.get("administrator"));
        peopleAssignments.setBusinessAdministrators(adminsEntities);
        
        task.setPeopleAssignments(peopleAssignments);
        
        //Create associated Task Data
        TaskData data = new TaskData();
        //Mock ids
        data.setWorkItemId(1);
        data.setProcessInstanceId(1);
        data.setProcessSessionId(1);
        task.setTaskData(data);
        
        //create content parameters
        ContentData contentData = this.createContentData();
        
        //create task in Local Task Service
        localTaskService.addTask(task, contentData);

        //Clear form
        this.txtTaskName.setText("");
        this.cboAssignTo.setSelectedIndex(0);
        this.taskParametersTableModel.clear();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserjButtonActionPerformed
        if (userjTextField.getText() != null && !userjTextField.getText().equals("")) {
            User user = new User(userjTextField.getText());
            taskSession.addUser(user);
            users.put(userjTextField.getText(), user);
            this.synchronizeUserComboBoxModel();
        }

    }//GEN-LAST:event_addUserjButtonActionPerformed

    private void addGroupjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroupjButtonActionPerformed
        // TODO add your handling code here:
        if (groupjTextField.getText() != null && !groupjTextField.getText().equals("")) {
            Group group = new Group(groupjTextField.getText());
            taskSession.addGroup(group);
            groups.put(groupjTextField.getText(), group);
        }
    }//GEN-LAST:event_addGroupjButtonActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow();
            System.out.println("Double Clicked Row: "+row);
            selectTaskForm(target, row);
        }
    }//GEN-LAST:event_mouseClicked

    private void perspectivejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perspectivejComboBoxActionPerformed
        this.refreshTaskList();
    }//GEN-LAST:event_perspectivejComboBoxActionPerformed

    private void btnAddParamterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddParamterActionPerformed
        this.taskParametersTableModel.addRow();
    }//GEN-LAST:event_btnAddParamterActionPerformed

    private void btnDeleteParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteParameterActionPerformed
        int[] selectedRows = this.tblParameters.getSelectedRows();
        for (int i = selectedRows.length - 1; i == 0; i--) {
            this.taskParametersTableModel.deleteRowAt(selectedRows[i]);
        }
    }//GEN-LAST:event_btnDeleteParameterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TasksListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TasksListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TasksListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TasksListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TasksListUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroupjButton;
    private javax.swing.JButton addUserjButton;
    private javax.swing.JButton btnAddParamter;
    private javax.swing.JButton btnDeleteParameter;
    private javax.swing.JComboBox cboAssignTo;
    private javax.swing.JTextField groupjTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox perspectivejComboBox;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JComboBox selectedUserjComboBox;
    private javax.swing.JTable taskSummariesjTable;
    private javax.swing.JTabbedPane tasklistsjTabbedPane;
    private javax.swing.JTable tblFormsRegistry;
    private javax.swing.JTable tblParameters;
    private javax.swing.JTextField txtTaskName;
    private javax.swing.JTextField userjTextField;
    // End of variables declaration//GEN-END:variables

    private void initTaskComponents() {
        // Create an EntityManagerFactory based on the PU configuration
        emf = Persistence.createEntityManagerFactory("org.jbpm.task");
        // The Task Service will use the EMF to store our Task Status
        taskService = new TaskService(emf, SystemEventListenerFactory.getSystemEventListener());
        // We can uset the Task Service to get an instance of the Task Session which
        // allows us to introduce to our database the users and groups information before 
        // running our tests
        taskSession = taskService.createSession();
        
        //create new Local Task Service
        localTaskService = new LocalTaskService(taskService);
        
        //regisister task event listener to Local Task Service
        localTaskService.addEventListener(taskEventListener);
        
        // Adds 1 Administrator, 2 users and 1 Group
        addUsersAndGroups(taskSession);

        //We need to set up an user to represent the user that is making the requests
        MockUserInfo userInfo = new MockUserInfo();
        taskService.setUserinfo(userInfo);
        
        this.taskParametersTableModel = new TaskParametersTableModel();
        this.tblParameters.setColumnModel(new TaskParametersTableModel.ColumnModel());
        this.tblParameters.setModel(taskParametersTableModel);
    }

    private void addUsersAndGroups(TaskServiceSession taskSession) {
        User user = new User("salaboy");
        User watman = new User("watman");
        taskSession.addUser(user);
        taskSession.addUser(watman);
        User administrator = new User("Administrator");
        taskSession.addUser(administrator);
        users.put("salaboy", user);
        users.put("watman", watman);
        users.put("administrator", administrator);
        Group myGroup = new Group("group1");
        taskSession.addGroup(myGroup);
        groups.put("group1", myGroup);
        this.synchronizeUserComboBoxModel();
    }

    private void initTaskFormMappings() {
        taskForms.put("*", DynamicTaskForm.class );
        taskForms.put("Correct Flow Average!!!", OtherTaskForm.class);
        taskForms.put("My Simple Task", MySimpleTaskFormJPanel.class);
        
        this.formRegistryTableModel = new FormRegistryTableModel();
        this.tblFormsRegistry.setModel(formRegistryTableModel);
        
        for (Map.Entry<String, Class> entry : this.taskForms.entrySet()) {
            this.formRegistryTableModel.addRow(entry.getKey(), entry.getValue().getSimpleName());
        }
    }
    
    private void refreshTaskList(){
        String selectedUser = (String) selectedUserjComboBox.getSelectedItem();
        System.out.println("Selected User: " + selectedUser);
        List<TaskSummary> tasks = localTaskService.getTasksAssignedAsPotentialOwner(selectedUser, "en-UK");
        System.out.println("Tasks: " + tasks + " - size: " + tasks.size());
        String selectedPerspective = (String) perspectivejComboBox.getItemAt(perspectivejComboBox.getSelectedIndex());
        if (selectedPerspective.equals("Simple")) {
            taskSummariesjTable.setModel(new SimpleTaskSummariesModel(tasks));
        } else {
            taskSummariesjTable.setModel(new DetailedTaskSummariesModel(tasks));
        }
        
    }
    

    private void synchronizeUserComboBoxModel(){
        int cboAssignToIndex = this.cboAssignTo.getSelectedIndex();
        int selectedUserjComboBoxIndex = this.selectedUserjComboBox.getSelectedIndex();
        
        this.userComboBoxModel = new DefaultComboBoxModel();
        for (String user : this.users.keySet()) {
            this.userComboBoxModel.addElement(user);
        }
        
        this.cboAssignTo.setModel(userComboBoxModel);
        this.selectedUserjComboBox.setModel(userComboBoxModel);
        
        this.cboAssignTo.setSelectedIndex(cboAssignToIndex);
        this.selectedUserjComboBox.setSelectedIndex(selectedUserjComboBoxIndex);
    }

    
    /**
     * Creates a Map from the parameters table and marshalls it.
     * @return 
     */
    private ContentData createContentData(){
        
        Map<String, String> parameters = new LinkedHashMap<String, String>();

        int paramColumnIndex = TaskParametersTableModel.ColumnHeaders.PARAMETER.ordinal();
        int valueColumnIndex = TaskParametersTableModel.ColumnHeaders.VALUE.ordinal();
        
        for (int row = 0; row < this.taskParametersTableModel.getRowCount(); row++) {
            String paramName = (String) this.taskParametersTableModel.getValueAt(row, paramColumnIndex);
            String value = (String) this.taskParametersTableModel.getValueAt(row, valueColumnIndex);
            parameters.put(paramName, value);
        }
        
        return ContentMarshallerHelper.marshal(parameters, null);
    }
    
}
